#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Starting checks before commit'

# Check Prettier standards
npm run check-format ||
(
    echo 'Please format code into prettier formating standard';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo 'Please fullfill eslint standards '
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Please Make the typescript changes required above.'
    false;
)

# If everything passes... Now we can commit
echo 'All checks have passed building to final test'

npm run build ||
(
    echo 'Build failed , something is wrong 
    '
    false;
)

# If everything passes... Now we can commit
echo 'Commiting code now , everything is upto standard'
